pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                sh 'python3 --version'
                sh 'pip3 install -r requirements.txt'
            }
        }
        stage('Run') {
            steps {
                sh 'python3 app.py &'
            }
        }
    }
}
